#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 148
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 1
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 134

enum {
  aux_sym_matching_curlies_token1 = 1,
  sym__everything_else = 2,
  anon_sym_LBRACE_LBRACE = 3,
  anon_sym_RBRACE_RBRACE = 4,
  anon_sym_BSLASH_LBRACE = 5,
  anon_sym_BSLASH_RBRACE = 6,
  sym_opening_curly = 7,
  sym_closing_curly = 8,
  sym_equals = 9,
  sym_colon = 10,
  sym_fill_align = 11,
  sym_sign = 12,
  sym_hash = 13,
  sym_zero = 14,
  sym_min_width = 15,
  sym_precision = 16,
  sym_type = 17,
  sym_source_file = 18,
  sym_string_content = 19,
  sym_matching_curlies = 20,
  sym_format_specifiers = 21,
  sym_double_curlies = 22,
  sym_escaped_curly = 23,
  aux_sym_string_content_repeat1 = 24,
  aux_sym_matching_curlies_repeat1 = 25,
  alias_sym_nim_expression = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_matching_curlies_token1] = "matching_curlies_token1",
  [sym__everything_else] = "_everything_else",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_BSLASH_LBRACE] = "\\{",
  [anon_sym_BSLASH_RBRACE] = "\\}",
  [sym_opening_curly] = "opening_curly",
  [sym_closing_curly] = "closing_curly",
  [sym_equals] = "equals",
  [sym_colon] = "colon",
  [sym_fill_align] = "fill_align",
  [sym_sign] = "sign",
  [sym_hash] = "hash",
  [sym_zero] = "zero",
  [sym_min_width] = "min_width",
  [sym_precision] = "precision",
  [sym_type] = "type",
  [sym_source_file] = "source_file",
  [sym_string_content] = "string_content",
  [sym_matching_curlies] = "matching_curlies",
  [sym_format_specifiers] = "format_specifiers",
  [sym_double_curlies] = "double_curlies",
  [sym_escaped_curly] = "escaped_curly",
  [aux_sym_string_content_repeat1] = "string_content_repeat1",
  [aux_sym_matching_curlies_repeat1] = "matching_curlies_repeat1",
  [alias_sym_nim_expression] = "nim_expression",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_matching_curlies_token1] = aux_sym_matching_curlies_token1,
  [sym__everything_else] = sym__everything_else,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_BSLASH_LBRACE] = anon_sym_BSLASH_LBRACE,
  [anon_sym_BSLASH_RBRACE] = anon_sym_BSLASH_RBRACE,
  [sym_opening_curly] = sym_opening_curly,
  [sym_closing_curly] = sym_closing_curly,
  [sym_equals] = sym_equals,
  [sym_colon] = sym_colon,
  [sym_fill_align] = sym_fill_align,
  [sym_sign] = sym_sign,
  [sym_hash] = sym_hash,
  [sym_zero] = sym_zero,
  [sym_min_width] = sym_min_width,
  [sym_precision] = sym_precision,
  [sym_type] = sym_type,
  [sym_source_file] = sym_source_file,
  [sym_string_content] = sym_string_content,
  [sym_matching_curlies] = sym_matching_curlies,
  [sym_format_specifiers] = sym_format_specifiers,
  [sym_double_curlies] = sym_double_curlies,
  [sym_escaped_curly] = sym_escaped_curly,
  [aux_sym_string_content_repeat1] = aux_sym_string_content_repeat1,
  [aux_sym_matching_curlies_repeat1] = aux_sym_matching_curlies_repeat1,
  [alias_sym_nim_expression] = alias_sym_nim_expression,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_matching_curlies_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__everything_else] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_opening_curly] = {
    .visible = true,
    .named = true,
  },
  [sym_closing_curly] = {
    .visible = true,
    .named = true,
  },
  [sym_equals] = {
    .visible = true,
    .named = true,
  },
  [sym_colon] = {
    .visible = true,
    .named = true,
  },
  [sym_fill_align] = {
    .visible = true,
    .named = true,
  },
  [sym_sign] = {
    .visible = true,
    .named = true,
  },
  [sym_hash] = {
    .visible = true,
    .named = true,
  },
  [sym_zero] = {
    .visible = true,
    .named = true,
  },
  [sym_min_width] = {
    .visible = true,
    .named = true,
  },
  [sym_precision] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_matching_curlies] = {
    .visible = true,
    .named = true,
  },
  [sym_format_specifiers] = {
    .visible = true,
    .named = true,
  },
  [sym_double_curlies] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_curly] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_matching_curlies_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_nim_expression] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_closing_curly = 1,
  field_equals = 2,
  field_escaped_curly = 3,
  field_fill_align = 4,
  field_hash = 5,
  field_min_width = 6,
  field_nim_expression = 7,
  field_opening_curly = 8,
  field_precision = 9,
  field_sign = 10,
  field_type = 11,
  field_zero = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_closing_curly] = "closing_curly",
  [field_equals] = "equals",
  [field_escaped_curly] = "escaped_curly",
  [field_fill_align] = "fill_align",
  [field_hash] = "hash",
  [field_min_width] = "min_width",
  [field_nim_expression] = "nim_expression",
  [field_opening_curly] = "opening_curly",
  [field_precision] = "precision",
  [field_sign] = "sign",
  [field_type] = "type",
  [field_zero] = "zero",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 4},
  [3] = {.index = 5, .length = 2},
  [4] = {.index = 7, .length = 5},
  [5] = {.index = 12, .length = 1},
  [6] = {.index = 13, .length = 1},
  [7] = {.index = 14, .length = 1},
  [8] = {.index = 15, .length = 1},
  [9] = {.index = 16, .length = 1},
  [10] = {.index = 17, .length = 1},
  [11] = {.index = 18, .length = 1},
  [12] = {.index = 19, .length = 4},
  [13] = {.index = 23, .length = 5},
  [14] = {.index = 28, .length = 2},
  [15] = {.index = 30, .length = 2},
  [16] = {.index = 32, .length = 2},
  [17] = {.index = 34, .length = 2},
  [18] = {.index = 36, .length = 2},
  [19] = {.index = 38, .length = 2},
  [20] = {.index = 40, .length = 2},
  [21] = {.index = 42, .length = 2},
  [22] = {.index = 44, .length = 2},
  [23] = {.index = 46, .length = 2},
  [24] = {.index = 48, .length = 2},
  [25] = {.index = 50, .length = 2},
  [26] = {.index = 52, .length = 2},
  [27] = {.index = 54, .length = 2},
  [28] = {.index = 56, .length = 2},
  [29] = {.index = 58, .length = 2},
  [30] = {.index = 60, .length = 2},
  [31] = {.index = 62, .length = 2},
  [32] = {.index = 64, .length = 2},
  [33] = {.index = 66, .length = 2},
  [34] = {.index = 68, .length = 2},
  [35] = {.index = 70, .length = 3},
  [36] = {.index = 73, .length = 3},
  [37] = {.index = 76, .length = 3},
  [38] = {.index = 79, .length = 3},
  [39] = {.index = 82, .length = 3},
  [40] = {.index = 85, .length = 3},
  [41] = {.index = 88, .length = 3},
  [42] = {.index = 91, .length = 3},
  [43] = {.index = 94, .length = 3},
  [44] = {.index = 97, .length = 3},
  [45] = {.index = 100, .length = 3},
  [46] = {.index = 103, .length = 3},
  [47] = {.index = 106, .length = 3},
  [48] = {.index = 109, .length = 3},
  [49] = {.index = 112, .length = 3},
  [50] = {.index = 115, .length = 3},
  [51] = {.index = 118, .length = 3},
  [52] = {.index = 121, .length = 3},
  [53] = {.index = 124, .length = 3},
  [54] = {.index = 127, .length = 3},
  [55] = {.index = 130, .length = 3},
  [56] = {.index = 133, .length = 3},
  [57] = {.index = 136, .length = 3},
  [58] = {.index = 139, .length = 3},
  [59] = {.index = 142, .length = 3},
  [60] = {.index = 145, .length = 3},
  [61] = {.index = 148, .length = 3},
  [62] = {.index = 151, .length = 3},
  [63] = {.index = 154, .length = 3},
  [64] = {.index = 157, .length = 3},
  [65] = {.index = 160, .length = 3},
  [66] = {.index = 163, .length = 3},
  [67] = {.index = 166, .length = 3},
  [68] = {.index = 169, .length = 3},
  [69] = {.index = 172, .length = 3},
  [70] = {.index = 175, .length = 4},
  [71] = {.index = 179, .length = 4},
  [72] = {.index = 183, .length = 4},
  [73] = {.index = 187, .length = 4},
  [74] = {.index = 191, .length = 4},
  [75] = {.index = 195, .length = 4},
  [76] = {.index = 199, .length = 4},
  [77] = {.index = 203, .length = 4},
  [78] = {.index = 207, .length = 4},
  [79] = {.index = 211, .length = 4},
  [80] = {.index = 215, .length = 4},
  [81] = {.index = 219, .length = 4},
  [82] = {.index = 223, .length = 4},
  [83] = {.index = 227, .length = 4},
  [84] = {.index = 231, .length = 4},
  [85] = {.index = 235, .length = 4},
  [86] = {.index = 239, .length = 4},
  [87] = {.index = 243, .length = 4},
  [88] = {.index = 247, .length = 4},
  [89] = {.index = 251, .length = 4},
  [90] = {.index = 255, .length = 4},
  [91] = {.index = 259, .length = 4},
  [92] = {.index = 263, .length = 4},
  [93] = {.index = 267, .length = 4},
  [94] = {.index = 271, .length = 4},
  [95] = {.index = 275, .length = 4},
  [96] = {.index = 279, .length = 4},
  [97] = {.index = 283, .length = 4},
  [98] = {.index = 287, .length = 4},
  [99] = {.index = 291, .length = 4},
  [100] = {.index = 295, .length = 4},
  [101] = {.index = 299, .length = 4},
  [102] = {.index = 303, .length = 4},
  [103] = {.index = 307, .length = 4},
  [104] = {.index = 311, .length = 4},
  [105] = {.index = 315, .length = 5},
  [106] = {.index = 320, .length = 5},
  [107] = {.index = 325, .length = 5},
  [108] = {.index = 330, .length = 5},
  [109] = {.index = 335, .length = 5},
  [110] = {.index = 340, .length = 5},
  [111] = {.index = 345, .length = 5},
  [112] = {.index = 350, .length = 5},
  [113] = {.index = 355, .length = 5},
  [114] = {.index = 360, .length = 5},
  [115] = {.index = 365, .length = 5},
  [116] = {.index = 370, .length = 5},
  [117] = {.index = 375, .length = 5},
  [118] = {.index = 380, .length = 5},
  [119] = {.index = 385, .length = 5},
  [120] = {.index = 390, .length = 5},
  [121] = {.index = 395, .length = 5},
  [122] = {.index = 400, .length = 5},
  [123] = {.index = 405, .length = 5},
  [124] = {.index = 410, .length = 5},
  [125] = {.index = 415, .length = 5},
  [126] = {.index = 420, .length = 6},
  [127] = {.index = 426, .length = 6},
  [128] = {.index = 432, .length = 6},
  [129] = {.index = 438, .length = 6},
  [130] = {.index = 444, .length = 6},
  [131] = {.index = 450, .length = 6},
  [132] = {.index = 456, .length = 6},
  [133] = {.index = 462, .length = 7},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_escaped_curly, 0},
  [1] =
    {field_closing_curly, 2},
    {field_escaped_curly, 1, .inherited = true},
    {field_nim_expression, 1},
    {field_opening_curly, 0},
  [5] =
    {field_escaped_curly, 0, .inherited = true},
    {field_escaped_curly, 1, .inherited = true},
  [7] =
    {field_closing_curly, 3},
    {field_equals, 2},
    {field_escaped_curly, 1, .inherited = true},
    {field_nim_expression, 1},
    {field_opening_curly, 0},
  [12] =
    {field_fill_align, 1},
  [13] =
    {field_sign, 1},
  [14] =
    {field_hash, 1},
  [15] =
    {field_zero, 1},
  [16] =
    {field_min_width, 1},
  [17] =
    {field_precision, 1},
  [18] =
    {field_type, 1},
  [19] =
    {field_closing_curly, 3},
    {field_escaped_curly, 1, .inherited = true},
    {field_nim_expression, 1},
    {field_opening_curly, 0},
  [23] =
    {field_closing_curly, 4},
    {field_equals, 2},
    {field_escaped_curly, 1, .inherited = true},
    {field_nim_expression, 1},
    {field_opening_curly, 0},
  [28] =
    {field_fill_align, 1},
    {field_sign, 2},
  [30] =
    {field_fill_align, 1},
    {field_hash, 2},
  [32] =
    {field_fill_align, 1},
    {field_zero, 2},
  [34] =
    {field_fill_align, 1},
    {field_min_width, 2},
  [36] =
    {field_fill_align, 1},
    {field_precision, 2},
  [38] =
    {field_fill_align, 1},
    {field_type, 2},
  [40] =
    {field_hash, 2},
    {field_sign, 1},
  [42] =
    {field_sign, 1},
    {field_zero, 2},
  [44] =
    {field_min_width, 2},
    {field_sign, 1},
  [46] =
    {field_precision, 2},
    {field_sign, 1},
  [48] =
    {field_sign, 1},
    {field_type, 2},
  [50] =
    {field_hash, 1},
    {field_zero, 2},
  [52] =
    {field_hash, 1},
    {field_min_width, 2},
  [54] =
    {field_hash, 1},
    {field_precision, 2},
  [56] =
    {field_hash, 1},
    {field_type, 2},
  [58] =
    {field_min_width, 2},
    {field_zero, 1},
  [60] =
    {field_precision, 2},
    {field_zero, 1},
  [62] =
    {field_type, 2},
    {field_zero, 1},
  [64] =
    {field_min_width, 1},
    {field_precision, 2},
  [66] =
    {field_min_width, 1},
    {field_type, 2},
  [68] =
    {field_precision, 1},
    {field_type, 2},
  [70] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_sign, 2},
  [73] =
    {field_fill_align, 1},
    {field_sign, 2},
    {field_zero, 3},
  [76] =
    {field_fill_align, 1},
    {field_min_width, 3},
    {field_sign, 2},
  [79] =
    {field_fill_align, 1},
    {field_precision, 3},
    {field_sign, 2},
  [82] =
    {field_fill_align, 1},
    {field_sign, 2},
    {field_type, 3},
  [85] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_zero, 3},
  [88] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_min_width, 3},
  [91] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_precision, 3},
  [94] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_type, 3},
  [97] =
    {field_fill_align, 1},
    {field_min_width, 3},
    {field_zero, 2},
  [100] =
    {field_fill_align, 1},
    {field_precision, 3},
    {field_zero, 2},
  [103] =
    {field_fill_align, 1},
    {field_type, 3},
    {field_zero, 2},
  [106] =
    {field_fill_align, 1},
    {field_min_width, 2},
    {field_precision, 3},
  [109] =
    {field_fill_align, 1},
    {field_min_width, 2},
    {field_type, 3},
  [112] =
    {field_fill_align, 1},
    {field_precision, 2},
    {field_type, 3},
  [115] =
    {field_hash, 2},
    {field_sign, 1},
    {field_zero, 3},
  [118] =
    {field_hash, 2},
    {field_min_width, 3},
    {field_sign, 1},
  [121] =
    {field_hash, 2},
    {field_precision, 3},
    {field_sign, 1},
  [124] =
    {field_hash, 2},
    {field_sign, 1},
    {field_type, 3},
  [127] =
    {field_min_width, 3},
    {field_sign, 1},
    {field_zero, 2},
  [130] =
    {field_precision, 3},
    {field_sign, 1},
    {field_zero, 2},
  [133] =
    {field_sign, 1},
    {field_type, 3},
    {field_zero, 2},
  [136] =
    {field_min_width, 2},
    {field_precision, 3},
    {field_sign, 1},
  [139] =
    {field_min_width, 2},
    {field_sign, 1},
    {field_type, 3},
  [142] =
    {field_precision, 2},
    {field_sign, 1},
    {field_type, 3},
  [145] =
    {field_hash, 1},
    {field_min_width, 3},
    {field_zero, 2},
  [148] =
    {field_hash, 1},
    {field_precision, 3},
    {field_zero, 2},
  [151] =
    {field_hash, 1},
    {field_type, 3},
    {field_zero, 2},
  [154] =
    {field_hash, 1},
    {field_min_width, 2},
    {field_precision, 3},
  [157] =
    {field_hash, 1},
    {field_min_width, 2},
    {field_type, 3},
  [160] =
    {field_hash, 1},
    {field_precision, 2},
    {field_type, 3},
  [163] =
    {field_min_width, 2},
    {field_precision, 3},
    {field_zero, 1},
  [166] =
    {field_min_width, 2},
    {field_type, 3},
    {field_zero, 1},
  [169] =
    {field_precision, 2},
    {field_type, 3},
    {field_zero, 1},
  [172] =
    {field_min_width, 1},
    {field_precision, 2},
    {field_type, 3},
  [175] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_sign, 2},
    {field_zero, 4},
  [179] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_min_width, 4},
    {field_sign, 2},
  [183] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_precision, 4},
    {field_sign, 2},
  [187] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_sign, 2},
    {field_type, 4},
  [191] =
    {field_fill_align, 1},
    {field_min_width, 4},
    {field_sign, 2},
    {field_zero, 3},
  [195] =
    {field_fill_align, 1},
    {field_precision, 4},
    {field_sign, 2},
    {field_zero, 3},
  [199] =
    {field_fill_align, 1},
    {field_sign, 2},
    {field_type, 4},
    {field_zero, 3},
  [203] =
    {field_fill_align, 1},
    {field_min_width, 3},
    {field_precision, 4},
    {field_sign, 2},
  [207] =
    {field_fill_align, 1},
    {field_min_width, 3},
    {field_sign, 2},
    {field_type, 4},
  [211] =
    {field_fill_align, 1},
    {field_precision, 3},
    {field_sign, 2},
    {field_type, 4},
  [215] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_min_width, 4},
    {field_zero, 3},
  [219] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_precision, 4},
    {field_zero, 3},
  [223] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_type, 4},
    {field_zero, 3},
  [227] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_min_width, 3},
    {field_precision, 4},
  [231] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_min_width, 3},
    {field_type, 4},
  [235] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_precision, 3},
    {field_type, 4},
  [239] =
    {field_fill_align, 1},
    {field_min_width, 3},
    {field_precision, 4},
    {field_zero, 2},
  [243] =
    {field_fill_align, 1},
    {field_min_width, 3},
    {field_type, 4},
    {field_zero, 2},
  [247] =
    {field_fill_align, 1},
    {field_precision, 3},
    {field_type, 4},
    {field_zero, 2},
  [251] =
    {field_fill_align, 1},
    {field_min_width, 2},
    {field_precision, 3},
    {field_type, 4},
  [255] =
    {field_hash, 2},
    {field_min_width, 4},
    {field_sign, 1},
    {field_zero, 3},
  [259] =
    {field_hash, 2},
    {field_precision, 4},
    {field_sign, 1},
    {field_zero, 3},
  [263] =
    {field_hash, 2},
    {field_sign, 1},
    {field_type, 4},
    {field_zero, 3},
  [267] =
    {field_hash, 2},
    {field_min_width, 3},
    {field_precision, 4},
    {field_sign, 1},
  [271] =
    {field_hash, 2},
    {field_min_width, 3},
    {field_sign, 1},
    {field_type, 4},
  [275] =
    {field_hash, 2},
    {field_precision, 3},
    {field_sign, 1},
    {field_type, 4},
  [279] =
    {field_min_width, 3},
    {field_precision, 4},
    {field_sign, 1},
    {field_zero, 2},
  [283] =
    {field_min_width, 3},
    {field_sign, 1},
    {field_type, 4},
    {field_zero, 2},
  [287] =
    {field_precision, 3},
    {field_sign, 1},
    {field_type, 4},
    {field_zero, 2},
  [291] =
    {field_min_width, 2},
    {field_precision, 3},
    {field_sign, 1},
    {field_type, 4},
  [295] =
    {field_hash, 1},
    {field_min_width, 3},
    {field_precision, 4},
    {field_zero, 2},
  [299] =
    {field_hash, 1},
    {field_min_width, 3},
    {field_type, 4},
    {field_zero, 2},
  [303] =
    {field_hash, 1},
    {field_precision, 3},
    {field_type, 4},
    {field_zero, 2},
  [307] =
    {field_hash, 1},
    {field_min_width, 2},
    {field_precision, 3},
    {field_type, 4},
  [311] =
    {field_min_width, 2},
    {field_precision, 3},
    {field_type, 4},
    {field_zero, 1},
  [315] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_min_width, 5},
    {field_sign, 2},
    {field_zero, 4},
  [320] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_precision, 5},
    {field_sign, 2},
    {field_zero, 4},
  [325] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_sign, 2},
    {field_type, 5},
    {field_zero, 4},
  [330] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_min_width, 4},
    {field_precision, 5},
    {field_sign, 2},
  [335] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_min_width, 4},
    {field_sign, 2},
    {field_type, 5},
  [340] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_precision, 4},
    {field_sign, 2},
    {field_type, 5},
  [345] =
    {field_fill_align, 1},
    {field_min_width, 4},
    {field_precision, 5},
    {field_sign, 2},
    {field_zero, 3},
  [350] =
    {field_fill_align, 1},
    {field_min_width, 4},
    {field_sign, 2},
    {field_type, 5},
    {field_zero, 3},
  [355] =
    {field_fill_align, 1},
    {field_precision, 4},
    {field_sign, 2},
    {field_type, 5},
    {field_zero, 3},
  [360] =
    {field_fill_align, 1},
    {field_min_width, 3},
    {field_precision, 4},
    {field_sign, 2},
    {field_type, 5},
  [365] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_min_width, 4},
    {field_precision, 5},
    {field_zero, 3},
  [370] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_min_width, 4},
    {field_type, 5},
    {field_zero, 3},
  [375] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_precision, 4},
    {field_type, 5},
    {field_zero, 3},
  [380] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_min_width, 3},
    {field_precision, 4},
    {field_type, 5},
  [385] =
    {field_fill_align, 1},
    {field_min_width, 3},
    {field_precision, 4},
    {field_type, 5},
    {field_zero, 2},
  [390] =
    {field_hash, 2},
    {field_min_width, 4},
    {field_precision, 5},
    {field_sign, 1},
    {field_zero, 3},
  [395] =
    {field_hash, 2},
    {field_min_width, 4},
    {field_sign, 1},
    {field_type, 5},
    {field_zero, 3},
  [400] =
    {field_hash, 2},
    {field_precision, 4},
    {field_sign, 1},
    {field_type, 5},
    {field_zero, 3},
  [405] =
    {field_hash, 2},
    {field_min_width, 3},
    {field_precision, 4},
    {field_sign, 1},
    {field_type, 5},
  [410] =
    {field_min_width, 3},
    {field_precision, 4},
    {field_sign, 1},
    {field_type, 5},
    {field_zero, 2},
  [415] =
    {field_hash, 1},
    {field_min_width, 3},
    {field_precision, 4},
    {field_type, 5},
    {field_zero, 2},
  [420] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_min_width, 5},
    {field_precision, 6},
    {field_sign, 2},
    {field_zero, 4},
  [426] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_min_width, 5},
    {field_sign, 2},
    {field_type, 6},
    {field_zero, 4},
  [432] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_precision, 5},
    {field_sign, 2},
    {field_type, 6},
    {field_zero, 4},
  [438] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_min_width, 4},
    {field_precision, 5},
    {field_sign, 2},
    {field_type, 6},
  [444] =
    {field_fill_align, 1},
    {field_min_width, 4},
    {field_precision, 5},
    {field_sign, 2},
    {field_type, 6},
    {field_zero, 3},
  [450] =
    {field_fill_align, 1},
    {field_hash, 2},
    {field_min_width, 4},
    {field_precision, 5},
    {field_type, 6},
    {field_zero, 3},
  [456] =
    {field_hash, 2},
    {field_min_width, 4},
    {field_precision, 5},
    {field_sign, 1},
    {field_type, 6},
    {field_zero, 3},
  [462] =
    {field_fill_align, 1},
    {field_hash, 3},
    {field_min_width, 5},
    {field_precision, 6},
    {field_sign, 2},
    {field_type, 7},
    {field_zero, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [1] = alias_sym_nim_expression,
  },
  [4] = {
    [1] = alias_sym_nim_expression,
  },
  [12] = {
    [1] = alias_sym_nim_expression,
  },
  [13] = {
    [1] = alias_sym_nim_expression,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_matching_curlies_repeat1, 2,
    aux_sym_matching_curlies_repeat1,
    alias_sym_nim_expression,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '0') ADVANCE(30);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '=') ADVANCE(23);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          lookahead == 'b' ||
          ('d' <= lookahead && lookahead <= 'g') ||
          lookahead == 'o' ||
          lookahead == 'x') ADVANCE(35);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(5);
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '0') ADVANCE(31);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6)
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(27);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '^') ADVANCE(25);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          lookahead == 'b' ||
          ('d' <= lookahead && lookahead <= 'g') ||
          lookahead == 'o' ||
          lookahead == 'x') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '0') ADVANCE(30);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          lookahead == 'b' ||
          ('d' <= lookahead && lookahead <= 'g') ||
          lookahead == 'o' ||
          lookahead == 'x') ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '=') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead != 0 &&
          lookahead != ':' &&
          lookahead != '{') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '^') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      END_STATE();
    case 7:
      if (lookahead == '}') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '^') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '^') ADVANCE(25);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 10:
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead == '=') ADVANCE(23);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11)
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '}') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12)
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_matching_curlies_token1);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_matching_curlies_token1);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead == '}') ADVANCE(20);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__everything_else);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_BSLASH_LBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BSLASH_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_opening_curly);
      if (lookahead == '{') ADVANCE(17);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_closing_curly);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_equals);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_colon);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_fill_align);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_sign);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_sign);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '^') ADVANCE(25);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_hash);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_hash);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '^') ADVANCE(25);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_zero);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_zero);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '^') ADVANCE(25);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_min_width);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '^') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_min_width);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_precision);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_type);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '^') ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_matching_curlies_token1] = ACTIONS(1),
    [sym__everything_else] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [sym_opening_curly] = ACTIONS(1),
    [sym_closing_curly] = ACTIONS(1),
    [sym_equals] = ACTIONS(1),
    [sym_colon] = ACTIONS(1),
    [sym_hash] = ACTIONS(1),
    [sym_zero] = ACTIONS(1),
    [sym_min_width] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(110),
    [sym_string_content] = STATE(119),
    [sym_matching_curlies] = STATE(6),
    [sym_double_curlies] = STATE(6),
    [aux_sym_string_content_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__everything_else] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(7),
    [sym_opening_curly] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(11), 1,
      aux_sym_matching_curlies_token1,
    ACTIONS(15), 1,
      sym_closing_curly,
    ACTIONS(17), 1,
      sym_equals,
    ACTIONS(19), 1,
      sym_colon,
    STATE(3), 1,
      aux_sym_matching_curlies_repeat1,
    STATE(10), 1,
      sym_escaped_curly,
    STATE(104), 1,
      sym_format_specifiers,
    ACTIONS(13), 2,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_RBRACE,
  [26] = 5,
    ACTIONS(21), 1,
      aux_sym_matching_curlies_token1,
    STATE(3), 1,
      aux_sym_matching_curlies_repeat1,
    STATE(10), 1,
      sym_escaped_curly,
    ACTIONS(24), 2,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_RBRACE,
    ACTIONS(27), 3,
      sym_closing_curly,
      sym_equals,
      sym_colon,
  [45] = 8,
    ACTIONS(29), 1,
      sym_closing_curly,
    ACTIONS(31), 1,
      sym_fill_align,
    ACTIONS(33), 1,
      sym_sign,
    ACTIONS(35), 1,
      sym_hash,
    ACTIONS(37), 1,
      sym_zero,
    ACTIONS(39), 1,
      sym_min_width,
    ACTIONS(41), 1,
      sym_precision,
    ACTIONS(43), 1,
      sym_type,
  [70] = 5,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      sym__everything_else,
    ACTIONS(53), 1,
      sym_opening_curly,
    ACTIONS(50), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
    STATE(5), 3,
      sym_matching_curlies,
      sym_double_curlies,
      aux_sym_string_content_repeat1,
  [89] = 5,
    ACTIONS(9), 1,
      sym_opening_curly,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      sym__everything_else,
    ACTIONS(7), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
    STATE(5), 3,
      sym_matching_curlies,
      sym_double_curlies,
      aux_sym_string_content_repeat1,
  [108] = 7,
    ACTIONS(60), 1,
      sym_closing_curly,
    ACTIONS(62), 1,
      sym_sign,
    ACTIONS(64), 1,
      sym_hash,
    ACTIONS(66), 1,
      sym_zero,
    ACTIONS(68), 1,
      sym_min_width,
    ACTIONS(70), 1,
      sym_precision,
    ACTIONS(72), 1,
      sym_type,
  [130] = 2,
    ACTIONS(74), 1,
      aux_sym_matching_curlies_token1,
    ACTIONS(76), 5,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_RBRACE,
      sym_closing_curly,
      sym_equals,
      sym_colon,
  [141] = 2,
    ACTIONS(78), 1,
      aux_sym_matching_curlies_token1,
    ACTIONS(80), 5,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_RBRACE,
      sym_closing_curly,
      sym_equals,
      sym_colon,
  [152] = 2,
    ACTIONS(82), 1,
      aux_sym_matching_curlies_token1,
    ACTIONS(84), 5,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_RBRACE,
      sym_closing_curly,
      sym_equals,
      sym_colon,
  [163] = 6,
    ACTIONS(86), 1,
      sym_closing_curly,
    ACTIONS(88), 1,
      sym_hash,
    ACTIONS(90), 1,
      sym_zero,
    ACTIONS(92), 1,
      sym_min_width,
    ACTIONS(94), 1,
      sym_precision,
    ACTIONS(96), 1,
      sym_type,
  [182] = 6,
    ACTIONS(98), 1,
      sym_closing_curly,
    ACTIONS(100), 1,
      sym_hash,
    ACTIONS(102), 1,
      sym_zero,
    ACTIONS(104), 1,
      sym_min_width,
    ACTIONS(106), 1,
      sym_precision,
    ACTIONS(108), 1,
      sym_type,
  [201] = 4,
    ACTIONS(11), 1,
      aux_sym_matching_curlies_token1,
    STATE(2), 1,
      aux_sym_matching_curlies_repeat1,
    STATE(10), 1,
      sym_escaped_curly,
    ACTIONS(13), 2,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_RBRACE,
  [215] = 5,
    ACTIONS(110), 1,
      sym_closing_curly,
    ACTIONS(112), 1,
      sym_zero,
    ACTIONS(114), 1,
      sym_min_width,
    ACTIONS(116), 1,
      sym_precision,
    ACTIONS(118), 1,
      sym_type,
  [231] = 2,
    ACTIONS(122), 1,
      sym_opening_curly,
    ACTIONS(120), 4,
      ts_builtin_sym_end,
      sym__everything_else,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [241] = 2,
    ACTIONS(126), 1,
      sym_opening_curly,
    ACTIONS(124), 4,
      ts_builtin_sym_end,
      sym__everything_else,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [251] = 5,
    ACTIONS(128), 1,
      sym_closing_curly,
    ACTIONS(130), 1,
      sym_zero,
    ACTIONS(132), 1,
      sym_min_width,
    ACTIONS(134), 1,
      sym_precision,
    ACTIONS(136), 1,
      sym_type,
  [267] = 5,
    ACTIONS(138), 1,
      sym_closing_curly,
    ACTIONS(140), 1,
      sym_zero,
    ACTIONS(142), 1,
      sym_min_width,
    ACTIONS(144), 1,
      sym_precision,
    ACTIONS(146), 1,
      sym_type,
  [283] = 2,
    ACTIONS(150), 1,
      sym_opening_curly,
    ACTIONS(148), 4,
      ts_builtin_sym_end,
      sym__everything_else,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [293] = 2,
    ACTIONS(154), 1,
      sym_opening_curly,
    ACTIONS(152), 4,
      ts_builtin_sym_end,
      sym__everything_else,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [303] = 2,
    ACTIONS(158), 1,
      sym_opening_curly,
    ACTIONS(156), 4,
      ts_builtin_sym_end,
      sym__everything_else,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
  [313] = 5,
    ACTIONS(160), 1,
      sym_closing_curly,
    ACTIONS(162), 1,
      sym_zero,
    ACTIONS(164), 1,
      sym_min_width,
    ACTIONS(166), 1,
      sym_precision,
    ACTIONS(168), 1,
      sym_type,
  [329] = 4,
    ACTIONS(170), 1,
      sym_closing_curly,
    ACTIONS(172), 1,
      sym_min_width,
    ACTIONS(174), 1,
      sym_precision,
    ACTIONS(176), 1,
      sym_type,
  [342] = 4,
    ACTIONS(178), 1,
      sym_closing_curly,
    ACTIONS(180), 1,
      sym_min_width,
    ACTIONS(182), 1,
      sym_precision,
    ACTIONS(184), 1,
      sym_type,
  [355] = 4,
    ACTIONS(186), 1,
      sym_closing_curly,
    ACTIONS(188), 1,
      sym_min_width,
    ACTIONS(190), 1,
      sym_precision,
    ACTIONS(192), 1,
      sym_type,
  [368] = 4,
    ACTIONS(194), 1,
      sym_closing_curly,
    ACTIONS(196), 1,
      sym_min_width,
    ACTIONS(198), 1,
      sym_precision,
    ACTIONS(200), 1,
      sym_type,
  [381] = 4,
    ACTIONS(202), 1,
      sym_closing_curly,
    ACTIONS(204), 1,
      sym_min_width,
    ACTIONS(206), 1,
      sym_precision,
    ACTIONS(208), 1,
      sym_type,
  [394] = 4,
    ACTIONS(210), 1,
      sym_closing_curly,
    ACTIONS(212), 1,
      sym_min_width,
    ACTIONS(214), 1,
      sym_precision,
    ACTIONS(216), 1,
      sym_type,
  [407] = 4,
    ACTIONS(218), 1,
      sym_closing_curly,
    ACTIONS(220), 1,
      sym_min_width,
    ACTIONS(222), 1,
      sym_precision,
    ACTIONS(224), 1,
      sym_type,
  [420] = 4,
    ACTIONS(226), 1,
      sym_closing_curly,
    ACTIONS(228), 1,
      sym_min_width,
    ACTIONS(230), 1,
      sym_precision,
    ACTIONS(232), 1,
      sym_type,
  [433] = 3,
    ACTIONS(234), 1,
      sym_closing_curly,
    ACTIONS(236), 1,
      sym_precision,
    ACTIONS(238), 1,
      sym_type,
  [443] = 3,
    ACTIONS(240), 1,
      sym_closing_curly,
    ACTIONS(242), 1,
      sym_precision,
    ACTIONS(244), 1,
      sym_type,
  [453] = 3,
    ACTIONS(246), 1,
      sym_closing_curly,
    ACTIONS(248), 1,
      sym_precision,
    ACTIONS(250), 1,
      sym_type,
  [463] = 3,
    ACTIONS(252), 1,
      sym_closing_curly,
    ACTIONS(254), 1,
      sym_precision,
    ACTIONS(256), 1,
      sym_type,
  [473] = 3,
    ACTIONS(258), 1,
      sym_closing_curly,
    ACTIONS(260), 1,
      sym_precision,
    ACTIONS(262), 1,
      sym_type,
  [483] = 3,
    ACTIONS(264), 1,
      sym_closing_curly,
    ACTIONS(266), 1,
      sym_precision,
    ACTIONS(268), 1,
      sym_type,
  [493] = 3,
    ACTIONS(270), 1,
      sym_closing_curly,
    ACTIONS(272), 1,
      sym_precision,
    ACTIONS(274), 1,
      sym_type,
  [503] = 3,
    ACTIONS(276), 1,
      sym_closing_curly,
    ACTIONS(278), 1,
      sym_precision,
    ACTIONS(280), 1,
      sym_type,
  [513] = 3,
    ACTIONS(282), 1,
      sym_closing_curly,
    ACTIONS(284), 1,
      sym_precision,
    ACTIONS(286), 1,
      sym_type,
  [523] = 3,
    ACTIONS(288), 1,
      sym_closing_curly,
    ACTIONS(290), 1,
      sym_precision,
    ACTIONS(292), 1,
      sym_type,
  [533] = 3,
    ACTIONS(294), 1,
      sym_closing_curly,
    ACTIONS(296), 1,
      sym_precision,
    ACTIONS(298), 1,
      sym_type,
  [543] = 3,
    ACTIONS(19), 1,
      sym_colon,
    ACTIONS(300), 1,
      sym_closing_curly,
    STATE(95), 1,
      sym_format_specifiers,
  [553] = 3,
    ACTIONS(302), 1,
      sym_closing_curly,
    ACTIONS(304), 1,
      sym_precision,
    ACTIONS(306), 1,
      sym_type,
  [563] = 3,
    ACTIONS(308), 1,
      sym_closing_curly,
    ACTIONS(310), 1,
      sym_precision,
    ACTIONS(312), 1,
      sym_type,
  [573] = 3,
    ACTIONS(314), 1,
      sym_closing_curly,
    ACTIONS(316), 1,
      sym_precision,
    ACTIONS(318), 1,
      sym_type,
  [583] = 3,
    ACTIONS(320), 1,
      sym_closing_curly,
    ACTIONS(322), 1,
      sym_precision,
    ACTIONS(324), 1,
      sym_type,
  [593] = 3,
    ACTIONS(326), 1,
      sym_closing_curly,
    ACTIONS(328), 1,
      sym_precision,
    ACTIONS(330), 1,
      sym_type,
  [603] = 2,
    ACTIONS(332), 1,
      sym_closing_curly,
    ACTIONS(334), 1,
      sym_type,
  [610] = 2,
    ACTIONS(336), 1,
      sym_closing_curly,
    ACTIONS(338), 1,
      sym_type,
  [617] = 2,
    ACTIONS(340), 1,
      sym_closing_curly,
    ACTIONS(342), 1,
      sym_type,
  [624] = 2,
    ACTIONS(344), 1,
      sym_closing_curly,
    ACTIONS(346), 1,
      sym_type,
  [631] = 2,
    ACTIONS(348), 1,
      sym_closing_curly,
    ACTIONS(350), 1,
      sym_type,
  [638] = 2,
    ACTIONS(352), 1,
      sym_closing_curly,
    ACTIONS(354), 1,
      sym_type,
  [645] = 2,
    ACTIONS(356), 1,
      sym_closing_curly,
    ACTIONS(358), 1,
      sym_type,
  [652] = 2,
    ACTIONS(360), 1,
      sym_closing_curly,
    ACTIONS(362), 1,
      sym_type,
  [659] = 2,
    ACTIONS(364), 1,
      sym_closing_curly,
    ACTIONS(366), 1,
      sym_type,
  [666] = 2,
    ACTIONS(368), 1,
      sym_closing_curly,
    ACTIONS(370), 1,
      sym_type,
  [673] = 2,
    ACTIONS(372), 1,
      sym_closing_curly,
    ACTIONS(374), 1,
      sym_type,
  [680] = 2,
    ACTIONS(376), 1,
      sym_closing_curly,
    ACTIONS(378), 1,
      sym_type,
  [687] = 2,
    ACTIONS(380), 1,
      sym_closing_curly,
    ACTIONS(382), 1,
      sym_type,
  [694] = 2,
    ACTIONS(384), 1,
      sym_closing_curly,
    ACTIONS(386), 1,
      sym_type,
  [701] = 2,
    ACTIONS(388), 1,
      sym_closing_curly,
    ACTIONS(390), 1,
      sym_type,
  [708] = 2,
    ACTIONS(392), 1,
      sym_closing_curly,
    ACTIONS(394), 1,
      sym_type,
  [715] = 2,
    ACTIONS(396), 1,
      sym_closing_curly,
    ACTIONS(398), 1,
      sym_type,
  [722] = 2,
    ACTIONS(400), 1,
      sym_closing_curly,
    ACTIONS(402), 1,
      sym_type,
  [729] = 2,
    ACTIONS(404), 1,
      sym_closing_curly,
    ACTIONS(406), 1,
      sym_type,
  [736] = 2,
    ACTIONS(408), 1,
      sym_closing_curly,
    ACTIONS(410), 1,
      sym_type,
  [743] = 2,
    ACTIONS(412), 1,
      sym_closing_curly,
    ACTIONS(414), 1,
      sym_type,
  [750] = 2,
    ACTIONS(416), 1,
      sym_closing_curly,
    ACTIONS(418), 1,
      sym_type,
  [757] = 2,
    ACTIONS(420), 1,
      sym_closing_curly,
    ACTIONS(422), 1,
      sym_type,
  [764] = 2,
    ACTIONS(424), 1,
      sym_closing_curly,
    ACTIONS(426), 1,
      sym_type,
  [771] = 2,
    ACTIONS(428), 1,
      sym_closing_curly,
    ACTIONS(430), 1,
      sym_type,
  [778] = 2,
    ACTIONS(432), 1,
      sym_closing_curly,
    ACTIONS(434), 1,
      sym_type,
  [785] = 2,
    ACTIONS(436), 1,
      sym_closing_curly,
    ACTIONS(438), 1,
      sym_type,
  [792] = 2,
    ACTIONS(440), 1,
      sym_closing_curly,
    ACTIONS(442), 1,
      sym_type,
  [799] = 2,
    ACTIONS(444), 1,
      sym_closing_curly,
    ACTIONS(446), 1,
      sym_type,
  [806] = 2,
    ACTIONS(448), 1,
      sym_closing_curly,
    ACTIONS(450), 1,
      sym_type,
  [813] = 2,
    ACTIONS(452), 1,
      sym_closing_curly,
    ACTIONS(454), 1,
      sym_type,
  [820] = 2,
    ACTIONS(456), 1,
      sym_closing_curly,
    ACTIONS(458), 1,
      sym_type,
  [827] = 1,
    ACTIONS(460), 1,
      sym_closing_curly,
  [831] = 1,
    ACTIONS(462), 1,
      sym_closing_curly,
  [835] = 1,
    ACTIONS(464), 1,
      sym_closing_curly,
  [839] = 1,
    ACTIONS(466), 1,
      sym_closing_curly,
  [843] = 1,
    ACTIONS(468), 1,
      sym_closing_curly,
  [847] = 1,
    ACTIONS(470), 1,
      sym_closing_curly,
  [851] = 1,
    ACTIONS(472), 1,
      sym_closing_curly,
  [855] = 1,
    ACTIONS(474), 1,
      sym_closing_curly,
  [859] = 1,
    ACTIONS(476), 1,
      sym_closing_curly,
  [863] = 1,
    ACTIONS(478), 1,
      sym_closing_curly,
  [867] = 1,
    ACTIONS(480), 1,
      sym_closing_curly,
  [871] = 1,
    ACTIONS(482), 1,
      sym_closing_curly,
  [875] = 1,
    ACTIONS(484), 1,
      sym_closing_curly,
  [879] = 1,
    ACTIONS(486), 1,
      sym_closing_curly,
  [883] = 1,
    ACTIONS(488), 1,
      sym_closing_curly,
  [887] = 1,
    ACTIONS(490), 1,
      sym_closing_curly,
  [891] = 1,
    ACTIONS(492), 1,
      sym_closing_curly,
  [895] = 1,
    ACTIONS(494), 1,
      sym_closing_curly,
  [899] = 1,
    ACTIONS(496), 1,
      sym_closing_curly,
  [903] = 1,
    ACTIONS(498), 1,
      sym_closing_curly,
  [907] = 1,
    ACTIONS(500), 1,
      sym_closing_curly,
  [911] = 1,
    ACTIONS(502), 1,
      sym_closing_curly,
  [915] = 1,
    ACTIONS(504), 1,
      sym_closing_curly,
  [919] = 1,
    ACTIONS(506), 1,
      sym_closing_curly,
  [923] = 1,
    ACTIONS(508), 1,
      sym_closing_curly,
  [927] = 1,
    ACTIONS(510), 1,
      sym_closing_curly,
  [931] = 1,
    ACTIONS(512), 1,
      sym_closing_curly,
  [935] = 1,
    ACTIONS(514), 1,
      sym_closing_curly,
  [939] = 1,
    ACTIONS(516), 1,
      sym_closing_curly,
  [943] = 1,
    ACTIONS(518), 1,
      sym_closing_curly,
  [947] = 1,
    ACTIONS(520), 1,
      ts_builtin_sym_end,
  [951] = 1,
    ACTIONS(522), 1,
      sym_closing_curly,
  [955] = 1,
    ACTIONS(524), 1,
      sym_closing_curly,
  [959] = 1,
    ACTIONS(526), 1,
      sym_closing_curly,
  [963] = 1,
    ACTIONS(528), 1,
      sym_closing_curly,
  [967] = 1,
    ACTIONS(530), 1,
      sym_closing_curly,
  [971] = 1,
    ACTIONS(532), 1,
      sym_closing_curly,
  [975] = 1,
    ACTIONS(534), 1,
      sym_closing_curly,
  [979] = 1,
    ACTIONS(536), 1,
      sym_closing_curly,
  [983] = 1,
    ACTIONS(538), 1,
      ts_builtin_sym_end,
  [987] = 1,
    ACTIONS(540), 1,
      sym_closing_curly,
  [991] = 1,
    ACTIONS(542), 1,
      sym_closing_curly,
  [995] = 1,
    ACTIONS(544), 1,
      sym_closing_curly,
  [999] = 1,
    ACTIONS(546), 1,
      sym_closing_curly,
  [1003] = 1,
    ACTIONS(548), 1,
      sym_closing_curly,
  [1007] = 1,
    ACTIONS(550), 1,
      sym_closing_curly,
  [1011] = 1,
    ACTIONS(552), 1,
      sym_closing_curly,
  [1015] = 1,
    ACTIONS(554), 1,
      sym_closing_curly,
  [1019] = 1,
    ACTIONS(556), 1,
      sym_closing_curly,
  [1023] = 1,
    ACTIONS(558), 1,
      sym_closing_curly,
  [1027] = 1,
    ACTIONS(560), 1,
      sym_closing_curly,
  [1031] = 1,
    ACTIONS(562), 1,
      sym_closing_curly,
  [1035] = 1,
    ACTIONS(564), 1,
      sym_closing_curly,
  [1039] = 1,
    ACTIONS(566), 1,
      sym_closing_curly,
  [1043] = 1,
    ACTIONS(568), 1,
      sym_closing_curly,
  [1047] = 1,
    ACTIONS(570), 1,
      sym_closing_curly,
  [1051] = 1,
    ACTIONS(572), 1,
      sym_closing_curly,
  [1055] = 1,
    ACTIONS(574), 1,
      sym_closing_curly,
  [1059] = 1,
    ACTIONS(576), 1,
      sym_closing_curly,
  [1063] = 1,
    ACTIONS(578), 1,
      sym_closing_curly,
  [1067] = 1,
    ACTIONS(580), 1,
      sym_closing_curly,
  [1071] = 1,
    ACTIONS(582), 1,
      sym_closing_curly,
  [1075] = 1,
    ACTIONS(584), 1,
      sym_closing_curly,
  [1079] = 1,
    ACTIONS(586), 1,
      sym_closing_curly,
  [1083] = 1,
    ACTIONS(588), 1,
      sym_closing_curly,
  [1087] = 1,
    ACTIONS(590), 1,
      sym_closing_curly,
  [1091] = 1,
    ACTIONS(592), 1,
      sym_closing_curly,
  [1095] = 1,
    ACTIONS(594), 1,
      sym_closing_curly,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 45,
  [SMALL_STATE(5)] = 70,
  [SMALL_STATE(6)] = 89,
  [SMALL_STATE(7)] = 108,
  [SMALL_STATE(8)] = 130,
  [SMALL_STATE(9)] = 141,
  [SMALL_STATE(10)] = 152,
  [SMALL_STATE(11)] = 163,
  [SMALL_STATE(12)] = 182,
  [SMALL_STATE(13)] = 201,
  [SMALL_STATE(14)] = 215,
  [SMALL_STATE(15)] = 231,
  [SMALL_STATE(16)] = 241,
  [SMALL_STATE(17)] = 251,
  [SMALL_STATE(18)] = 267,
  [SMALL_STATE(19)] = 283,
  [SMALL_STATE(20)] = 293,
  [SMALL_STATE(21)] = 303,
  [SMALL_STATE(22)] = 313,
  [SMALL_STATE(23)] = 329,
  [SMALL_STATE(24)] = 342,
  [SMALL_STATE(25)] = 355,
  [SMALL_STATE(26)] = 368,
  [SMALL_STATE(27)] = 381,
  [SMALL_STATE(28)] = 394,
  [SMALL_STATE(29)] = 407,
  [SMALL_STATE(30)] = 420,
  [SMALL_STATE(31)] = 433,
  [SMALL_STATE(32)] = 443,
  [SMALL_STATE(33)] = 453,
  [SMALL_STATE(34)] = 463,
  [SMALL_STATE(35)] = 473,
  [SMALL_STATE(36)] = 483,
  [SMALL_STATE(37)] = 493,
  [SMALL_STATE(38)] = 503,
  [SMALL_STATE(39)] = 513,
  [SMALL_STATE(40)] = 523,
  [SMALL_STATE(41)] = 533,
  [SMALL_STATE(42)] = 543,
  [SMALL_STATE(43)] = 553,
  [SMALL_STATE(44)] = 563,
  [SMALL_STATE(45)] = 573,
  [SMALL_STATE(46)] = 583,
  [SMALL_STATE(47)] = 593,
  [SMALL_STATE(48)] = 603,
  [SMALL_STATE(49)] = 610,
  [SMALL_STATE(50)] = 617,
  [SMALL_STATE(51)] = 624,
  [SMALL_STATE(52)] = 631,
  [SMALL_STATE(53)] = 638,
  [SMALL_STATE(54)] = 645,
  [SMALL_STATE(55)] = 652,
  [SMALL_STATE(56)] = 659,
  [SMALL_STATE(57)] = 666,
  [SMALL_STATE(58)] = 673,
  [SMALL_STATE(59)] = 680,
  [SMALL_STATE(60)] = 687,
  [SMALL_STATE(61)] = 694,
  [SMALL_STATE(62)] = 701,
  [SMALL_STATE(63)] = 708,
  [SMALL_STATE(64)] = 715,
  [SMALL_STATE(65)] = 722,
  [SMALL_STATE(66)] = 729,
  [SMALL_STATE(67)] = 736,
  [SMALL_STATE(68)] = 743,
  [SMALL_STATE(69)] = 750,
  [SMALL_STATE(70)] = 757,
  [SMALL_STATE(71)] = 764,
  [SMALL_STATE(72)] = 771,
  [SMALL_STATE(73)] = 778,
  [SMALL_STATE(74)] = 785,
  [SMALL_STATE(75)] = 792,
  [SMALL_STATE(76)] = 799,
  [SMALL_STATE(77)] = 806,
  [SMALL_STATE(78)] = 813,
  [SMALL_STATE(79)] = 820,
  [SMALL_STATE(80)] = 827,
  [SMALL_STATE(81)] = 831,
  [SMALL_STATE(82)] = 835,
  [SMALL_STATE(83)] = 839,
  [SMALL_STATE(84)] = 843,
  [SMALL_STATE(85)] = 847,
  [SMALL_STATE(86)] = 851,
  [SMALL_STATE(87)] = 855,
  [SMALL_STATE(88)] = 859,
  [SMALL_STATE(89)] = 863,
  [SMALL_STATE(90)] = 867,
  [SMALL_STATE(91)] = 871,
  [SMALL_STATE(92)] = 875,
  [SMALL_STATE(93)] = 879,
  [SMALL_STATE(94)] = 883,
  [SMALL_STATE(95)] = 887,
  [SMALL_STATE(96)] = 891,
  [SMALL_STATE(97)] = 895,
  [SMALL_STATE(98)] = 899,
  [SMALL_STATE(99)] = 903,
  [SMALL_STATE(100)] = 907,
  [SMALL_STATE(101)] = 911,
  [SMALL_STATE(102)] = 915,
  [SMALL_STATE(103)] = 919,
  [SMALL_STATE(104)] = 923,
  [SMALL_STATE(105)] = 927,
  [SMALL_STATE(106)] = 931,
  [SMALL_STATE(107)] = 935,
  [SMALL_STATE(108)] = 939,
  [SMALL_STATE(109)] = 943,
  [SMALL_STATE(110)] = 947,
  [SMALL_STATE(111)] = 951,
  [SMALL_STATE(112)] = 955,
  [SMALL_STATE(113)] = 959,
  [SMALL_STATE(114)] = 963,
  [SMALL_STATE(115)] = 967,
  [SMALL_STATE(116)] = 971,
  [SMALL_STATE(117)] = 975,
  [SMALL_STATE(118)] = 979,
  [SMALL_STATE(119)] = 983,
  [SMALL_STATE(120)] = 987,
  [SMALL_STATE(121)] = 991,
  [SMALL_STATE(122)] = 995,
  [SMALL_STATE(123)] = 999,
  [SMALL_STATE(124)] = 1003,
  [SMALL_STATE(125)] = 1007,
  [SMALL_STATE(126)] = 1011,
  [SMALL_STATE(127)] = 1015,
  [SMALL_STATE(128)] = 1019,
  [SMALL_STATE(129)] = 1023,
  [SMALL_STATE(130)] = 1027,
  [SMALL_STATE(131)] = 1031,
  [SMALL_STATE(132)] = 1035,
  [SMALL_STATE(133)] = 1039,
  [SMALL_STATE(134)] = 1043,
  [SMALL_STATE(135)] = 1047,
  [SMALL_STATE(136)] = 1051,
  [SMALL_STATE(137)] = 1055,
  [SMALL_STATE(138)] = 1059,
  [SMALL_STATE(139)] = 1063,
  [SMALL_STATE(140)] = 1067,
  [SMALL_STATE(141)] = 1071,
  [SMALL_STATE(142)] = 1075,
  [SMALL_STATE(143)] = 1079,
  [SMALL_STATE(144)] = 1083,
  [SMALL_STATE(145)] = 1087,
  [SMALL_STATE(146)] = 1091,
  [SMALL_STATE(147)] = 1095,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_matching_curlies_repeat1, 2, .production_id = 3), SHIFT_REPEAT(8),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_matching_curlies_repeat1, 2, .production_id = 3), SHIFT_REPEAT(9),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_matching_curlies_repeat1, 2, .production_id = 3),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format_specifiers, 1),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_content_repeat1, 2),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_content_repeat1, 2), SHIFT_REPEAT(5),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_content_repeat1, 2), SHIFT_REPEAT(16),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_content_repeat1, 2), SHIFT_REPEAT(13),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_content, 1),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format_specifiers, 2, .production_id = 5),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_matching_curlies_repeat1, 1),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_matching_curlies_repeat1, 1),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escaped_curly, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escaped_curly, 1),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_matching_curlies_repeat1, 1, .production_id = 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_matching_curlies_repeat1, 1, .production_id = 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 14),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 2, .production_id = 6),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 35),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_matching_curlies, 4, .production_id = 4),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_matching_curlies, 4, .production_id = 4),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_curlies, 1),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_curlies, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 2, .production_id = 7),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 20),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_matching_curlies, 4, .production_id = 12),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_matching_curlies, 4, .production_id = 12),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_matching_curlies, 5, .production_id = 13),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_matching_curlies, 5, .production_id = 13),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_matching_curlies, 3, .production_id = 2),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_matching_curlies, 3, .production_id = 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 15),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 50),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 25),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 36),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 21),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 2, .production_id = 8),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 40),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 70),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 16),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 71),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 17),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 60),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 105),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 2, .production_id = 9),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 22),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 54),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 51),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 74),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 26),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 80),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 29),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 90),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 37),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 41),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 44),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 61),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 66),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 30),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 7, .production_id = 126),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [348] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 32),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 120),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 115),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [360] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 38),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [364] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 111),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [368] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 42),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [372] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 108),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [376] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 45),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [380] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 106),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [384] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 47),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [388] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 100),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [392] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 96),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [396] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 93),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [400] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 27),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [404] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 52),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [408] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 91),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [412] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 86),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [416] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 55),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [420] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 83),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [424] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 57),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [428] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 77),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [432] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 2, .production_id = 10),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [436] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 23),
  [438] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [440] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 75),
  [442] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [444] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 18),
  [446] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [448] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 63),
  [450] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [452] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 81),
  [454] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [456] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 72),
  [458] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [460] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 58),
  [462] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 99),
  [464] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 59),
  [466] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 19),
  [468] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 62),
  [470] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 64),
  [472] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 65),
  [474] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 67),
  [476] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 68),
  [478] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 69),
  [480] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 2, .production_id = 11),
  [482] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 73),
  [484] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 76),
  [486] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 78),
  [488] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 79),
  [490] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [492] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 82),
  [494] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 31),
  [496] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 84),
  [498] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 85),
  [500] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 56),
  [502] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 87),
  [504] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 88),
  [506] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 89),
  [508] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [510] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 24),
  [512] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 92),
  [514] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 53),
  [516] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 94),
  [518] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 95),
  [520] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [522] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 97),
  [524] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 98),
  [526] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 28),
  [528] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 49),
  [530] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 101),
  [532] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 102),
  [534] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 103),
  [536] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 5, .production_id = 104),
  [538] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [540] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 48),
  [542] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 107),
  [544] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 46),
  [546] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 109),
  [548] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 110),
  [550] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 43),
  [552] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 112),
  [554] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 113),
  [556] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 114),
  [558] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 4, .production_id = 39),
  [560] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 116),
  [562] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 117),
  [564] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 118),
  [566] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 119),
  [568] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 34),
  [570] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 121),
  [572] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 122),
  [574] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 123),
  [576] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 124),
  [578] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 6, .production_id = 125),
  [580] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 3, .production_id = 33),
  [582] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 7, .production_id = 127),
  [584] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 7, .production_id = 128),
  [586] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 7, .production_id = 129),
  [588] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 7, .production_id = 130),
  [590] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 7, .production_id = 131),
  [592] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 7, .production_id = 132),
  [594] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_specifiers, 8, .production_id = 133),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_nim_format_string(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
